app:
  name: Spring Cloud App
  description: Welcome to ${app.name}

my:
  greeting: Hello World from Spring Cloud Config Server
  list:
    values: One,Two,Three

db:
  connection: config-server-uri
  host: 127.0.0.1
  port: 5000